---
Name: modular-config
---
Injector:
  Application:
    class: Modular\Application
  Debugger:
    class: Modular\Debugger

ContentController:
  extensions:
    - Modular\Extensions\Controller\Content
#    - Modular\Extensions\Controller\Requirements # added by mosaic

Modular\Controllers\Model:
  extensions:
    - Modular\Extensions\Controller\Model
