---
Name: modular-config
---
Director:
  rules:
    'gridlist//$Action/$PageID': Modular\GridList\Controllers\Standalone
ContentController:
  extensions:
    - Modular\ContentControllerExtension
Injector:
  GridListService:
    class: Modular\GridList\Service
  Application:
    class: Modular\Application
  Debugger:
    class: Modular\Debugger
Modular\Blocks\Block:
  skip_duplicate_related_classes:
    - 'Page'
    - 'File'
    - 'Modular\Models\Tag'
    - 'Modular\Models\GridListFilter'
