---
Name: modular-config
---
Director:
  rules:
    'gridlist//$Action/$PageID': Modular\GridList\Controllers\Standalone
ContentController:
  extensions:
    - Modular\ContentControllerExtension
Injector:
  Application: Modular\Application
  Debugger: Modular\Debugger
  GridListService:
    class: Modular\GridList\Service